# docker-compose.yml
version: '3'
services:
    composer:
        image: composer:latest
        environment:
            - COMPOSER_CACHE_DIR=/app/.cache/composer
        volumes:
            - .:/app
    php:
        image: php:8.1-cli
        volumes:
            - .:/app
        working_dir: /app
    fpm:
        image: php:8.1-fpm
        restart: always
        volumes:
            - .:/app
    phpunit:
        image: php:8.1-cli
        volumes:
            - .:/app
        working_dir: /app